%close all;
% clearvars

import Inputs.*
import Solvers.*
import Solvers.Mixture.*

%Inputs
inputSet = InputSet( ...
            modelFilePath         = './inputs/models.inp',  modelID    = 'MFVALS', ...
            optionsFilePath       = './inputs/options.inp', optionsID  = 'DEFAULT', ...
            geometryFilePath      = './inputs/geom.inp',    geometryID = 'MFVAL', ...
            bcFilePath            = './inputs/bc_Regime2_c.inp', ...
            sessionParentDir      = fullfile(pwd,'outputs'), ...
            overwriteSessionFiles = true, ...
            LOGMODE               = 'BOTH');
warning on 
% inputSet = InputSet( ...
%             modelFilePath         = './inputs/models.inp',  modelID    = 'MFVALS', ...
%             optionsFilePath       = './inputs/options.inp', optionsID  = 'STEADY', ...
%             geometryFilePath      = './inputs/geom.inp',    geometryID = 'MFVAL', ...
%             bcFilePath            = './inputs/bc_mfval_subcooled.inp', ...
%             sessionParentDir      = fullfile(pwd,'outputs'), ...
%             overwriteSessionFiles = true, ...
%             LOGMODE               = 'BOTH');
        
%inputSet = InputSet( ...
%           modelFilePath         = './inputs/models.inp',  modelID    = 'BARCS', ...
%            optionsFilePath       = './inputs/options.inp', optionsID  = 'STEADY', ...
%            geometryFilePath      = './inputs/geom.inp',    geometryID = 'BARC', ...
%            bcFilePath            = './inputs/bc_barc.inp', ...
%            sessionParentDir      = fullfile(pwd,'outputs'), ...
%            overwriteSessionFiles = true, ...
%            LOGMODE               = 'BOTH');    

%% Four-field

import Solvers.FourField.*

% Create the three-field solver
ffSolver = FourFieldSolver(inputSet);
ffSolver.plotz(1);                                                         % Plot initialization state (dep and ent set to 0 but calculated value is plotted instead)

% tfSolver is initialized at construction. Here, it is explicitly initialized for clarity.
ffSolver.initializeSolver(); 

% Solve (does not accept any argument)
ffSolver.solve();

% Axial and temporal plots
ffSolver.plotz(1);
ffSolver.plotz(ffSolver.NTIME);

% Save results
ffSolver.saveResults(saveFormat="MAT");