%% Obstructed Solver

warning off
%{
inputSet = Inputs.InputSet( ...
    modelFilePath = './inputs/models.inp', modelID = 'BARCS', ...
    optionsFilePath = './inputs/options.inp', optionsID = 'DEFAULT', ...
    geometryFilePath = './inputs/geom.inp', geometryID = 'BARC', ...
    bcFilePath = './inputs/bc_barc.inp', ...
    obsFilePath = './inputs/obstruction.inp', obsIDs = {'ROD'}, ...
    sessionParentDir = fullfile(pwd,'outputs'), ...
    overwriteSessionFiles = true, ...
    LOGMODE = 'BOTH');
%}

  inputSet= Inputs.InputSet( ...
             modelFilePath         = './inputs/models.inp',  modelID    = 'MFVALS', ...
             optionsFilePath       = './inputs/options.inp', optionsID  = 'OBS', ...
             geometryFilePath      = './inputs/geom.inp',    geometryID = 'MFVAL_obs', ...
             bcFilePath            = './inputs/bc_mfval_obs.inp', ...
             obsFilePath = './inputs/obstruction.inp', obsIDs = {'LARGEOBS'}, ...
             sessionParentDir      = fullfile(pwd,'outputs'), ...
             overwriteSessionFiles = true, ...
             LOGMODE               = 'BOTH');
%}

obsSolver = Solvers.Obstruction.ObstructionSolver(inputSet, 'THREEFIELD');

obsSolver.solve();

obsSolver.solveWallHT();

%%
% Ploting
%Plot the three field model results for the three tracks merged together
obsSolver.plotz('display','WL')
%%
%Plot the wall temperature distribution
obsSolver.plotWallTemperature();
