%% Non Obstructed Solver
clear vars

%Import Inputs and Solvers classes
import Inputs.*
import Solvers.*

%turn of warnings during initial setup
warning off
%Create input set 
%Inputs
 %inputSet_no_obs = InputSet( ...
 %           modelFilePath         = './inputs/models.inp',  modelID    = 'BARCS', ...
 %           optionsFilePath       = './inputs/options.inp', optionsID  = 'DEFAULT', ...
 %           geometryFilePath      = './inputs/geom.inp',    geometryID = 'BARC', ...
 %           bcFilePath            = './inputs/bc_barc.inp', ...
 %           sessionParentDir      = fullfile(pwd,'outputs'), ...
 %           overwriteSessionFiles = true, ...
 %           LOGMODE               = 'BOTH');

  inputSet_no_obs = Inputs.InputSet( ...
             modelFilePath         = './inputs/models.inp',  modelID    = 'MFVALS', ...
             optionsFilePath       = './inputs/options.inp', optionsID  = 'DEFAULT', ...
             geometryFilePath      = './inputs/geom.inp',    geometryID = 'MFVAL_obs', ...
             bcFilePath            = './inputs/bc_mfval_obs.inp', ...
             sessionParentDir      = fullfile(pwd,'outputs'), ...
             overwriteSessionFiles = true, ...
             LOGMODE               = 'BOTH');
%Turn warnings back on 
warning on

%import mixture solver class
import Solvers.Mixture.*
% Create the mixture solver
mixSolver = MixtureSolver(inputSet_no_obs);
%initialize the mixture solver
mixSolver.initializeSolver();
%solve the mixture solver
mixSolver.solve();
%plot the mixture solver mass flow rate results 
mixSolver.plotz('display','W');

%import three-field solver class
import Solvers.ThreeField.*
% Create the three-field solver
tfSolver = ThreeFieldSolver(inputSet_no_obs, mixSolver);                                                        
%Solve the three-field solver
tfSolver.solve();
%Plot the three-field solver mass flow rate results
tfSolver.plotz('display','W');

%% Obstructed Solver

warning off
%inputSet = Inputs.InputSet( ...
%    modelFilePath = './inputs/models.inp', modelID = 'BARCS', ...
%    optionsFilePath = './inputs/options.inp', optionsID = 'DEFAULT', ...
%    geometryFilePath = './inputs/geom.inp', geometryID = 'BARC', ...
%    bcFilePath = './inputs/bc_barc.inp', ...
%    obsFilePath = './inputs/obstruction.inp', obsIDs = {'ROD'}, ...
%    sessionParentDir = fullfile(pwd,'outputs'), ...
%    overwriteSessionFiles = true, ...
%    LOGMODE = 'BOTH');

  inputSet= Inputs.InputSet( ...
             modelFilePath         = './inputs/models.inp',  modelID    = 'MFVALS', ...
             optionsFilePath       = './inputs/options.inp', optionsID  = 'OBS', ...
             geometryFilePath      = './inputs/geom.inp',    geometryID = 'MFVAL_obs', ...
             bcFilePath            = './inputs/bc_mfval_obs.inp', ...
             obsFilePath = './inputs/obstruction.inp', obsIDs = {'LARGEOBS'}, ...
             sessionParentDir      = fullfile(pwd,'outputs'), ...
             overwriteSessionFiles = true, ...
             LOGMODE               = 'BOTH');


obsSolver = Solvers.Obstruction.ObstructionSolver(inputSet, 'THREEFIELD');
% obsSolver = Solvers.Obstruction.ObstructionSolver(inputSet, 'FOURFIELD');

obsSolver.solve();
%%
%Test segmentation is consistent
fprintf('Checking mass flow rate consistency across segments\n')
fprintf('segment1 last node  film W = %.6f\n', obsSolver.solutionSets(1).solver.film(1).W(end,1));
fprintf('segment2 first node filmW = %.6f\n', obsSolver.solutionSets(2).solver.film(1).W(1,1));
fprintf('segment1 last node  drop W = %.6f\n', obsSolver.solutionSets(1).solver.drop(1).W(end,1));
fprintf('segment2 first node drop W = %.6f\n', obsSolver.solutionSets(2).solver.drop(1).W(1));
fprintf('segment2 last node  film W = %.6f\n', obsSolver.solutionSets(2).solver.film(1).W(end,1));
fprintf('segment3 first node film W = %.6f\n', obsSolver.solutionSets(3).solver.film(1).W(1,1));
fprintf('segment2 last node  drop W = %.6f\n', obsSolver.solutionSets(2).solver.drop(1).W(end,1));
fprintf('segment3 first node drop W = %.6f\n', obsSolver.solutionSets(3).solver.drop(1).W(1));

%% 
% Ploting
%Plot the three field model results for the three tracks merged together
obsSolver.plotz('display','WL')
