addpath(genpath('..'));
inputSet = Inputs.InputSet( ...
    modelFilePath='../inputs/models.inp', modelID='BARCS', ...
    optionsFilePath='../inputs/options.inp', optionsID='DEFAULT', ...
    geometryFilePath='../inputs/geom.inp', geometryID='BARC', ...
    bcFilePath='../inputs/bc_barc.inp', ...
    obsFilePath='../inputs/obstruction.inp', obsIDs={'ROD'}, ...
    sessionParentDir=fullfile(pwd,'outputs'), ...
    overwriteSessionFiles=true, ...
    LOGMODE='BOTH');
obsSolver = Solvers.Obstruction.ObstructionSolver(inputSet, 'THREEFIELD');
obsSolver.solve();
fprintf('segment1 first node W = %.6f\n', obsSolver.solutionSets(1).solver.film(1).W(1,1));
fprintf('segment2 first node W = %.6f\n', obsSolver.solutionSets(2).solver.film(1).W(1,1));
fprintf('segment1 last node W = %.6f\n', obsSolver.solutionSets(1).solver.film(1).W(end,1));
fprintf('segment2 first node drop U = %.6f\n', obsSolver.solutionSets(2).solver.drop(1).U(1));
