name: MATLAB CI

on:
  push:
    branches:
      - matlab-ci
      - lecorre
      - main
  workflow_dispatch:

jobs:

  tests:
    #runs-on: ubuntu-latest
    runs-on: [self-hosted, linux, x64, matlab]

    strategy:
      # Try to run all the tests
      fail-fast: false
      # Over multiple versions
      matrix:
        include: ${{ fromJSON(
          (github.event_name == 'push' || github.event_name == 'workflow_dispatch') &&
          (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/matlab-ci')
          && '[
            {"matlab":"R2024b","python":"3.11"},
            {"matlab":"R2025b","python":"3.12"},
            {"matlab":"R2026b","python":"3.13"}
            ]'
          || '[
            {"matlab":"R2026b","python":"3.12"}
            ]'
          ) }}
          
    steps:

      #- name: Clean workspace
      #  run: rm -rf ./* .[^.]*

      - name: Checkout with submodules
        uses: actions/checkout@v7 
        with:
          submodules: true
          path: ./openstream

      - name: Checkout openstream-database
        uses: actions/checkout@v7
        with:
          repository: OpenSTREAM-solvers/openstream-database
          token:  ${{ secrets.ORG_REPO_TOKEN }}
          path: ./openstream-database
          ref: lecorre
      
      - name: Setup Python
        uses: actions/setup-python@v7
        with:
          python-version: ${{ matrix.python }}
          cache: pip
          cache-dependency-path: ./openstream/+CoolPropWrapper/requirements.txt
       
      - name: Install dependencies
        run: |
          pip install -r ./openstream/+CoolPropWrapper/requirements.txt

      # Sets up MATLAB on a GitHub-hosted runner
      #- name: Set up MATLAB
      #  uses: matlab-actions/setup-matlab@v3

      - name: Select MATLAB version
        run: |
          echo "/opt/MATLAB/${{ matrix.matlab }}/bin" >> "$GITHUB_PATH"
          
      - name: Query MATLAB version
        run: |
          echo "MATLAB:"
          which matlab
          matlab -batch "fprintf('Version: %s\n', version); fprintf('Root: %s\n', matlabroot); fprintf('Current working directory: %s\n', pwd);"

          echo
          echo "Python:"
          which python
          python --version
          python -m pip show nanobind
          
      # Runs a set of commands using the runners shell
      - name: Run all tests
        uses: matlab-actions/run-tests@v3
        with:
          output-detail: verbose
          source-folder: ./openstream

      # Upload artifacts
      - name: Upload MATLAB test output
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: matlab-output-${{ matrix.matlab }}
          path: |
            ./openstream/tests/+*/**
          if-no-files-found: warn
