name: Publish Sphinx docs to GitHub Pages

on:
  push:
    branches:
      - main
      - docs
      - lecorre
      - latexpdf-action

  workflow_dispatch:
    inputs:
        logLevel:
          description: 'Log level'
          required: true
          default: 'warning'
          type: choice
          options:
          - info
          - warning
          - debug

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout with submodules
        uses: actions/checkout@v7
        with:
          submodules: true

      - name: Setup Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.14'
          cache: pip
          cache-dependency-path: ./docs/source/requirements.txt

      - name: Install dependencies
        run: pip install -r ./docs/source/requirements.txt

      - name: Make html files
        run: make html
        working-directory: ./docs

      - name: Make latex file
        id: makelatex
        run: make latex
        working-directory: ./docs

      - name: Make pdf file
        id: makepdf
        uses: xu-cheng/latex-action@v4
        with:
          working_directory: ./docs/build/latex/
          root_file: OpenSTREAM.tex        

      #- name: Install TeXlive
      #  run: sudo apt-get update && sudo apt-get install texlive latexmk texlive-publishers texlive-science  cm-super
      #
      #- name: Make pdf file
      #  id: makepdf
      #  run: make latexpdf
      #  working-directory: ./docs

      - name: Copy pdf file
        if: steps.makepdf.outcome == 'success'
        run: mkdir -p ./build/html/files && cp ./build/latex/OpenSTREAM.pdf ./build/html/files/OpenSTREAM.pdf
        working-directory: ./docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html


